// La tabla de help() del motor: una línea por miembro. Vive aparte (pura, sin three) para que
// la prueba en Node pueda compararla con la API de src/index.js.

/** @type {import('./help.js').Member[]} */
export const ENGINE_MEMBERS = [
  ['renderer', 'el WebGLRenderer'],
  ['scene', 'la escena: la app cuelga lo suyo acá o en content'],
  ['camera', 'la cámara que dibuja: la PerspectiveCamera, o la OrthographicCamera en ortográfica (view.projection); mejor view que tocarla'],
  ['controls', 'lo que queda de los OrbitControls: { target, enabled, update() }; null con { controls: false } (sin la entrada del motor). Mejor view'],
  ['content', 'un grupo para lo de la app'],
  ['overlay', 'una escena que va encima de todo y fuera del post-proceso: gizmos, manijas'],
  ['composer', 'el EffectComposer (para sumar pases propios)'],
  ['preset', 'el preset puesto (una copia)'],
  ['setPreset(preset)', "cambiar cómo se ve: 'studio' | 'warm' | 'dark', un objeto, o { extends, … }"],
  ['tweak(over)', 'pisar algunos valores del preset actual: tweak({ sun: { intensity: 3 } })'],
  ['mode', "el modo de vista: 'render' | 'clay' | 'wireframe' | 'normals' | 'matcap' (se puede asignar)"],
  ['setMode(mode)', 'cambiar el modo de vista'],
  ['select(objects, { detail? })', 'contorno de selección; detail: además una línea fina por objeto'],
  ['selected', 'lo que está seleccionado'],
  ['show({ grid?, floor?, sky?, fog?, shadows? })', 'prender o apagar partes del estudio sin cambiar de preset; sin argumentos, cómo está'],
  ['hdri(source?, { background?, intensity?, blur?, rotation?, type? })', "el entorno HDRI: un panorama equirectangular (URL .hdr / .exr / imagen, o una THREE.Texture) que ilumina, se refleja y se ve de fondo, en el visor y en el render final; null lo saca; solo opciones cambia el que está; una Promise del estado; sin argumentos, cómo está"],
  ['edges({ enabled?, normalThreshold?, depthThreshold?, darken? })', 'contorno fino de geometría; sin argumentos, cómo está'],
  ['bloom({ enabled?, strength?, radius?, threshold? })', 'el bloom: lo que pasa de threshold se derrama (emisivos, reflejos fuertes); enabled es de la calidad; sin argumentos, cómo está'],
  ['ao({ enabled?, radius?, intensity?, samples? })', 'oclusión ambiental (GTAO): rincones, uniones y contacto con el piso; radius en fracción de area; enabled y samples son de la calidad; sin argumentos, cómo está'],
  ['quality(q?)', "la calidad (lo que cuesta GPU): 'baja' | 'media' | 'alta', o ajustes sueltos { antialias, shadows, shadowMapSize, ao, aoSamples, bloom, renderSamples, textures } que la vuelven 'personalizada'; sin argumentos, { name, …ajustes }"],
  ['suggestQuality()', "la calidad para arrancar según la placa: dedicada 'alta', integrada o software 'baja'"],
  ['onQualityChange(fn)', 'algo que corre cuando cambia la calidad (la app cambia sus texturas SD/HD); devuelve cómo sacarlo'],
  ['frame(objects?)', 'encuadrar la cámara en unos objetos, o en todo (lo mismo que view.fit)'],
  ['SCHEMES', "los esquemas de gestos: three, cad, blender (tablas { mouse, wheel, touch })"],
  ['KEYS', 'las teclas por defecto de view.input({ keyboard: true }), por code: flechas, +/−, numpad'],
  ['VIEWS', "las vistas con nombre: { front, back, right, left, top, bottom, iso }, cada una { dir, up }, para armar los botones"],
  ['view', 'la cámara con valores planos, sin tocar three: view.get(), view.set(), comandos, límites y avisos'],
  ['view.get()', "el estado de la cámara: { position, target, up, fov, projection, zoom }, serializable con JSON"],
  ['view.set(state, { animate? })', 'llevar la cámara a un estado; lo que no se pasa queda como está; una Promise (true si llegó, false si la cortaron)'],
  ['view.orbit(dYaw, dPitch, { around?, animate? })', 'orbitar en grados: yaw positivo a la derecha, pitch positivo hacia arriba; around: el punto que queda quieto'],
  ['view.pan(dx, dy, { unit?, animate? })', "desplazar en el plano de la pantalla (dx a la derecha, dy hacia arriba), en 'px' (por defecto) o 'world'"],
  ['view.zoom(factor, { at?, animate? })', 'acercar (2: el doble de grande); at: [x, y] en píxeles del visor que queda quieto (hacia el cursor)'],
  ['view.dolly(distance, { animate? })', 'avanzar hacia el objetivo en unidades de la escena (negativo: retroceder), sin pasarlo'],
  ['view.lookAt(point, { animate? })', 'mirar a un punto sin mover la cámara'],
  ['view.go(view, { fit?, margin?, projection?, animate? })', "ir a una vista ('front', 'top', 'iso', … o un { dir, up }) encuadrando fit: una caja { min, max }, unos objetos o todo (false: sin encuadrar); projection: cambiarla al llegar"],
  ['view.ray([x, y])', 'el rayo por un punto del visor (píxeles): { origin, dir }, con la cámara que dibuja; para elegir con el puntero'],
  ['view.project(point)', 'dónde cae un punto del mundo en el visor: [x, y, depth] (píxeles; depth de 0 a 1 entre near y far)'],
  ['view.worldPerPixel(point)', 'cuánto mide un píxel del visor en ese punto (en ortográfica, igual en todos lados): manijas de tamaño constante'],
  ['view.projection(p?)', "'perspective' | 'orthographic': el cambio no salta (el plano del objetivo se ve igual); sin argumentos, cuál está"],
  ['view.fit(boxOrObjects?, { margin?, animate? })', 'encuadrar sin cambiar de dirección una caja { min, max }, unos objetos o todo, con el aspecto de la pantalla'],
  ['view.limits({ minDistance?, maxDistance?, minPitch?, maxPitch?, floor? })', 'hasta dónde se mueve, por todos los caminos; floor: true no pasa debajo del piso; sin argumentos, cómo están'],
  ['view.onChange(fn)', 'algo que corre cuando cambia la cámara (una vez por cuadro, con el estado); devuelve cómo sacarlo'],
  ['view.onStart(fn)', 'algo que corre cuando la cámara empieza a moverse (el usuario o una animación); devuelve cómo sacarlo'],
  ['view.onEnd(fn)', 'algo que corre cuando la cámara se queda quieta (con la inercia terminada); devuelve cómo sacarlo'],
  ['view.input({ scheme?, zoomToCursor?, orbitAround?, keyboard? })', "cómo navega el usuario: scheme 'three' | 'cad' | 'blender' | una tabla; orbitAround 'target' | 'cursor' | 'selection'; keyboard false | true | una tabla; sin argumentos, cómo está"],
  ['view.drive({ orbit?, pan?, zoom? } | null)', 'entrada directa continua (joystick, SpaceMouse, botón mantenido): velocidades por segundo; null frena'],
  ['view.nudge({ orbit?, pan?, zoom? }, { animate? })', 'un impulso de un solo paso'],
  ['view.claim(fn)', "un filtro antes de cada gesto: si devuelve 'app', el gesto es de la app y la cámara no se mueve; devuelve cómo sacarlo"],
  ['view.suspend(name?)', 'bloquear la cámara para el usuario hasta soltar (con conteo: dos bloqueos no se pisan); devuelve cómo soltarlo'],
  ['view.suspended', 'los nombres de los bloqueos que hay'],
  ['snapshot({ width?, height?, type?, quality? })', 'una foto rápida del visor, como data URL'],
  ['render({ samples?, width?, height?, bounces?, camera?, onProgress?, signal?, type? })', 'el render final con path tracing: una Promise de la imagen (Blob)'],
  ['gpu({ print? })', "en qué placa se dibuja: { name, vendor, kind: 'discrete' | 'integrated' | 'software' | 'unknown', buffer, pixelRatio, maxMSAA, antialias }; la imprime en la consola"],
  ['resolution(value?, { min?, max?, fps? })', "con cuántos píxeles se dibuja el visor, en vivo: 1 nativa, 0.5 la mitad, o 'auto' (baja si no llega a los fps y sube si sobra); sin argumentos, cómo está"],
  ['onFrame(fn)', 'algo que corre en cada cuadro, antes de dibujar; devuelve cómo sacarlo'],
  ['onResize(fn)', 'algo que corre cuando cambian los píxeles del visor (ventana o resolución): { width, height, pixelRatio, drawingWidth, drawingHeight }; devuelve cómo sacarlo'],
  ['dispose()', 'soltar todo: loop, post-proceso y renderer'],
  ['help()', 'esta tabla'],
];
