// La tabla de help() del motor: una línea por miembro. Vive aparte (pura, sin three) para que
// la prueba en Node pueda compararla con la API de src/index.js.

/** @type {import('./help.js').Member[]} */
export const ENGINE_MEMBERS = [
  ['renderer', 'el WebGLRenderer'],
  ['scene', 'la escena: la app cuelga lo suyo acá o en content'],
  ['camera', 'la cámara (PerspectiveCamera)'],
  ['controls', 'los OrbitControls, o null si se creó con { controls: false }'],
  ['content', 'un grupo para lo de la app'],
  ['overlay', 'una escena que va encima de todo y fuera del post-proceso: gizmos, manijas'],
  ['composer', 'el EffectComposer (para sumar pases propios)'],
  ['preset', 'el preset puesto (una copia)'],
  ['setPreset(preset)', "cambiar cómo se ve: 'studio' | 'warm' | 'dark', un objeto, o { extends, … }"],
  ['tweak(over)', 'pisar algunos valores del preset actual: tweak({ sun: { intensity: 3 } })'],
  ['mode', "el modo de vista: 'render' | 'clay' | 'wireframe' | 'normals' | 'matcap' (se puede asignar)"],
  ['setMode(mode)', 'cambiar el modo de vista'],
  ['select(objects, { detail? })', 'contorno de selección; detail: además una línea fina por objeto'],
  ['selected', 'lo que está seleccionado'],
  ['show({ grid?, floor?, sky?, fog?, shadows? })', 'prender o apagar partes del estudio sin cambiar de preset; sin argumentos, cómo está'],
  ['edges({ enabled?, normalThreshold?, depthThreshold?, darken? })', 'contorno fino de geometría; sin argumentos, cómo está'],
  ['bloom({ enabled?, strength?, radius?, threshold? })', 'el bloom: lo que pasa de threshold se derrama (emisivos, reflejos fuertes); enabled es de la calidad; sin argumentos, cómo está'],
  ['ao({ enabled?, radius?, intensity?, samples? })', 'oclusión ambiental (GTAO): rincones, uniones y contacto con el piso; radius en fracción de area; enabled y samples son de la calidad; sin argumentos, cómo está'],
  ['quality(q?)', "la calidad (lo que cuesta GPU): 'baja' | 'media' | 'alta', o ajustes sueltos { antialias, shadows, shadowMapSize, ao, aoSamples, bloom, renderSamples, textures } que la vuelven 'personalizada'; sin argumentos, { name, …ajustes }"],
  ['suggestQuality()', "la calidad para arrancar según la placa: dedicada 'alta', integrada o software 'baja'"],
  ['onQualityChange(fn)', 'algo que corre cuando cambia la calidad (la app cambia sus texturas SD/HD); devuelve cómo sacarlo'],
  ['frame(objects?)', 'encuadrar la cámara en unos objetos, o en todo'],
  ['snapshot({ width?, height?, type?, quality? })', 'una foto rápida del visor, como data URL'],
  ['render({ samples?, width?, height?, bounces?, camera?, onProgress?, signal?, type? })', 'el render final con path tracing: una Promise de la imagen (Blob)'],
  ['gpu({ print? })', "en qué placa se dibuja: { name, vendor, kind: 'discrete' | 'integrated' | 'software' | 'unknown', buffer, pixelRatio, maxMSAA, antialias }; la imprime en la consola"],
  ['resolution(value?, { min?, max?, fps? })', "con cuántos píxeles se dibuja el visor, en vivo: 1 nativa, 0.5 la mitad, o 'auto' (baja si no llega a los fps y sube si sobra); sin argumentos, cómo está"],
  ['onFrame(fn)', 'algo que corre en cada cuadro, antes de dibujar; devuelve cómo sacarlo'],
  ['onResize(fn)', 'algo que corre cuando cambian los píxeles del visor (ventana o resolución): { width, height, pixelRatio, drawingWidth, drawingHeight }; devuelve cómo sacarlo'],
  ['dispose()', 'soltar todo: loop, post-proceso y renderer'],
  ['help()', 'esta tabla'],
];
